# -*- coding: utf-8 -*-
"""Linear Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1onld5QjHT2C4oJB6HfBqEOqzULNjI88h

##Diabities
"""

from sklearn import datasets

diabities=datasets.load_diabetes()

diabities

X=diabities.data
Y=diabities.target

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

from sklearn import linear_model
from sklearn.metrics import mean_squared_error , r2_score

model=linear_model.LinearRegression()

model.fit(X_train,Y_train)

Y_Pred=model.predict(X_test)

loss=mean_squared_error(Y_test,Y_Pred)
loss

coff=r2_score(Y_test,Y_Pred)
coff

import seaborn as sns

sns.scatterplot(Y_test,Y_Pred)

"""##Bosten Housing"""

! wget https://github.com/dataprofessor/data/raw/master/BostonHousing.csv

import pandas as pd

BostonHousing=pd.read_csv("BostonHousing.csv")

BostonHousing.head()

Y=BostonHousing.medv
X=BostonHousing.iloc[:,0:13]

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

from sklearn import linear_model
from sklearn.metrics import mean_squared_error,r2_score

model=linear_model.LinearRegression()
model.fit(X_train,Y_train)

y_pred=model.predict(X_test)

loss=mean_squared_error(Y_test,y_pred)
loss

r2_score(Y_test,y_pred)

import seaborn as sns 
sns.scatterplot(Y_test,y_pred)